# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package Git Action

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # schedule:
    # - cron: '*/30 * * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2    
        
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
          python-version: '3.x'
          architecture: 'x64'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Scraper with python
      run: |
        python app.py
    
    - name: Commits and Run
      run: |
        # git config --local user.email "trackin9issues@gmail.com"
        # git config --local user.name "Tracker" # 커밋에 포함될 이름
        git config --global user.email "trackin9issues@gmail.com"
        git config --global user.name "Tracker" # 커밋에 포함될 이름
        # git add .
        
        git add DfData.csv
        git commit -m "Auto - Update data with Scraping" # 커밋 메세지

        # git remote add origin https://github.com/TrackerIssues/0102_GitActNews.git
        # git branch -M main  
        # git push -u origin main

        
        # git remote set-url origin https://${{secrets.F1T}}@github.com/TrackerIssues/0102_GitActNews.git
        # git remote set-url origin https://TrackerIssues:${{secrets.F1T}}@github.com/TrackerIssues/0102_GitActNews.git
        git push

 
        
        
